# Generated by Django 5.1.4 on 2026-07-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_unit', models.CharField(max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('yield_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_unit', models.CharField(max_length=20)),
                ('prep_time_minutes', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_food_cost_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergen_info', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEVELOPMENT', 'Development'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatchProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=20, unique=True)),
                ('planned_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_check', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('CONDITIONAL', 'Conditional'), ('FAILED', 'Failed')], max_length=20)),
                ('quality_notes', models.TextField(blank=True)),
                ('substitution_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], default='IN_PROGRESS', max_length=20)),
                ('produced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_produced', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredientDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='kitchen.batchproduction')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='kitchen.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stock', to='kitchen.ingredient')),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_period', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('ALL_DAY', 'All day')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_items', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.productionplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='kitchen.recipe')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='batchproduction',
            name='plan_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='kitchen.productionplanitem'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('is_optional', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='kitchen.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kitchen.recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True)),
                ('qty_requested', models.DecimalField(decimal_places=3, max_digits=10)),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to='kitchen.ingredient')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.PositiveIntegerField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='kitchen.recipe')),
            ],
            options={
                'ordering': ['recipe_id', 'step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
