# Generated by Django 5.1.4 on 2026-07-09 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_codesequence_remove_kitchenstock_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.CharField(choices=[('OVER_PRODUCTION', 'Over-production'), ('PREP_WASTE', 'Prep waste'), ('SPOILAGE', 'Spoilage'), ('DROPPED', 'Dropped / accident'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('unit_cost_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_entries', to='kitchen.batchproduction')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wastage_entries', to='kitchen.ingredient')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
