# Generated by Django 5.1.4 on 2026-07-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_branch_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_CHEF', 'Head Chef'), ('KITCHEN_STAFF', 'Kitchen Staff'), ('MANAGER', 'Manager'), ('STORE_KEEPER', 'Store Keeper')], default='KITCHEN_STAFF', max_length=20),
        ),
    ]
